# Generated by Django 5.1.2 on 2024-11-04 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="image",
            name="users_like",
            field=models.ManyToManyField(
                blank=True, related_name="images_liked", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
